version: "3.7"
services:
    app:
        build:
            args:
                user: sorok
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: kube
        container_name: kube-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - kube

    db:
        image: mysql:8.0
        container_name: kube-db
        restart: unless-stopped
        ports:
            -   3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - kube

    nginx:
        image: nginx:alpine
        container_name: kube-nginx
        restart: unless-stopped
        ports:
            - 8002:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - kube

networks:
    kube:
        driver: bridge
